version: '3.9'

services:
  db:
    image: postgres:14
    volumes:
      - ./shared/postgresql:/var/lib/postgresql/data:Z
    env_file:
      - ./backend/.env

  app:
    build:
      context: .
      dockerfile: .devops/django/Dockerfile
      args:
        DJANGO_ENV: local
        USER_ID: "1000"
    depends_on:
      - db
      - redis
    env_file:
      - ./backend/.env

  redis:
    image: redis:6
