# Generated by Django 4.2.5 on 2023-10-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_remove_recipeingredient_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.IntegerField(verbose_name="Amount (g)"),
        ),
    ]
