# Generated by Django 4.2.5 on 2023-10-04 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_alter_recipeingredient_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="description",
        ),
    ]
