# Generated by Django 4.2.5 on 2023-10-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_remove_recipe_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Amount (g)"
            ),
        ),
    ]
