# Generated by Django 4.2.5 on 2023-10-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0008_recipeingredient_unit_alter_recipeingredient_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Amount"
            ),
        ),
    ]
