# Generated by Django 4.2.5 on 2023-10-04 20:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("calories", models.IntegerField()),
                ("protein", models.IntegerField()),
                ("fat", models.IntegerField()),
                ("carbohydrates", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FODMAPInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "fodmap",
                    models.CharField(
                        choices=[
                            (1, "Fructose"),
                            (2, "Lactose"),
                            (3, "Mannitol"),
                            (4, "Sorbitol"),
                            (5, "Gos"),
                            (6, "Fructans"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "fodmap_level",
                    models.CharField(
                        choices=[(1, "High"), (2, "Moderate"), (3, "Safe")],
                        max_length=255,
                    ),
                ),
                ("serving_size", models.IntegerField()),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ingredients.ingredient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
