# Generated by Django 4.2.5 on 2023-10-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="carbohydrates",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="fat",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="protein",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
