# Generated by Django 4.2.5 on 2023-10-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ingredients",
            "0002_alter_ingredient_carbohydrates_alter_ingredient_fat_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fodmapinfo",
            name="fodmap",
            field=models.IntegerField(
                choices=[
                    (1, "Fructose"),
                    (2, "Lactose"),
                    (3, "Mannitol"),
                    (4, "Sorbitol"),
                    (5, "Gos"),
                    (6, "Fructans"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="fodmapinfo",
            name="fodmap_level",
            field=models.IntegerField(
                choices=[(1, "High"), (2, "Moderate"), (3, "Safe")]
            ),
        ),
    ]
