# Generated by Django 4.2.5 on 2023-10-04 20:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ingredients", "0004_alter_fodmapinfo_fodmap"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="carbohydrates",
            new_name="carbs",
        ),
    ]
