# Generated by Django 4.2.5 on 2023-10-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingredients", "0005_rename_carbohydrates_ingredient_carbs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredient",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
