# Generated by Django 4.2.5 on 2023-10-08 11:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("ingredients", "0006_alter_ingredient_options_alter_ingredient_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "Gram"),
                            ("ml", "Milliliter"),
                            ("pcs", "Piece"),
                            ("tsp", "Teaspoon"),
                            ("tbsp", "Tablespoon"),
                            ("cup", "Cup"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "grams",
                    models.DecimalField(
                        decimal_places=2, help_text="Grams per unit", max_digits=5
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurement",
                        to="ingredients.ingredient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
