# Generated by Django 4.2.5 on 2023-10-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingredients", "0007_ingredientmeasurement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fodmapinfo",
            name="fodmap_level",
        ),
        migrations.RemoveField(
            model_name="fodmapinfo",
            name="serving_size",
        ),
        migrations.AddField(
            model_name="fodmapinfo",
            name="green_serving_size",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fodmapinfo",
            name="red_serving_size",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fodmapinfo",
            name="yellow_serving_size",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="fodmapinfo",
            name="fodmap",
            field=models.IntegerField(
                choices=[
                    (1, "Fructose"),
                    (2, "Lactose"),
                    (3, "Mannitol"),
                    (4, "Sorbitol"),
                    (5, "Gos"),
                    (6, "Fructans"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
    ]
