# Generated by Django 4.2.5 on 2023-10-14 17:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingredients", "0010_remove_fodmapinfo_fodmap_fodmapinfo_fodmaps_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fodmapinfo",
            name="fodmaps",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    choices=[
                        (1, "Fructose"),
                        (2, "Lactose"),
                        (3, "Mannitol"),
                        (4, "Sorbitol"),
                        (5, "Gos"),
                        (6, "Fructans"),
                    ]
                ),
                default=list,
                size=None,
            ),
        ),
    ]
