# Generated by Django 4.2.5 on 2023-10-14 17:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingredients", "0011_alter_fodmapinfo_fodmaps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fodmapinfo",
            name="fodmaps",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("fructose", "Fructose"),
                        ("lactose", "Lactose"),
                        ("mannitol", "Mannitol"),
                        ("sorbitol", "Sorbitol"),
                        ("gos", "Gos"),
                        ("fructans", "Fructans"),
                    ],
                    max_length=16,
                ),
                default=list,
                size=None,
            ),
        ),
    ]
